// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gglayniuiepgfapvusjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbGF5bml1aWVwZ2ZhcHZ1c2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzU3ODgsImV4cCI6MjA3MzE1MTc4OH0.v7UFjmZgxfO4143vMSi6n6nEQHHbldbxNyIq45KILEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});